[pytest]
; 注释掉pytest‑split分片执行，本项目没有原本的split配置
; addopts = -vs --split
; 保留allure报告配置
addopts = -vs --alluredir=./allure-results
testpaths = ./tests ./api
python_files = test_*.py
python_classes = Test*
python_functions = test_*
