[pytest]
markers = 
        smoke: smoke测试用例
        regression: 回归测试用例
; addopts = -vs --split
; 保留allure报告配置
addopts = -vs --alluredir=./allure-results
testpaths = ./tests ./api
python_files = test_*.py
python_classes = Test*
python_functions = test_*
