[pytest]
markers = 
        smoke: smoke测试用例
        regression: 回归测试用例
# 所有参数合并到同一个addopts
addopts = -vs --reruns=2 --reruns-delay=3 --alluredir=./allure-results
testpaths = ./tests ./api
python_files = test_*.py
python_classes = Test*
python_functions = test_*
